Updated CI

diff --git a/.github/workflows/create_tag.yml b/.github/workflows/create_tag.yml
--- a/.github/workflows/create_tag.yml
+++ b/.github/workflows/create_tag.yml
@@ -14,91 +14,318 @@ on:
     types: [closed]
     branches:
       - 'rel-*'
+      - 'main'
 
 jobs:
   create-tag-on-merge:
-    runs-on: self-hosted
-    if: "contains(github.base_ref, 'rel-') && github.event.pull_request.merged"
+    runs-on: ubuntu-latest
+    outputs:
+      tag_ref_output: ${{ steps.tag_output.outputs.tag_ref }}
+    env:
+       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
+    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
     steps:
-      - name: Find commit to tag
-        id: commit
-        uses: actions/github-script@v4
+      - uses: actions/checkout@v3
         with:
-          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
-          script: |
-            console.log("${{ github.event.pull_request.merge_commit_sha }}")
-            core.setOutput("commit_to_tag", "${{ github.event.pull_request.merge_commit_sha }}")
+          fetch-depth: 0
 
       - name: Find latest tag
+        run: |
+          latest_tags+=("$(git tag --contains '${{ github.event.pull_request.base.sha }}')")
+          for tag in $latest_tags; do tag_arr+=($tag); done
+          echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
         id: latest_tag
-        uses: actions/github-script@v4
+
+      - name: Create tag and update ref
+        uses: actions/github-script@v6.3.3
+        id: create_tag
         with:
-          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
+          github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
           script: |
-            console.log("${{ github.ref }}")
-            parts = "${{ github.ref }}".split('/')
-            branch_name = parts[parts.length - 1]
-            if (branch_name.startsWith('rel-') == false) {
-              console.log("Not matching.")
-            }
-            parts = branch_name.split('.')
-            branch_part = parts.slice(0, parts.length - 1).join('.')
-            per_page = 50
-            page = 1
-            all_tags = []
-            max_patch_no = 1
-            while (true) {
-              result = await github.repos.listTags({
-                owner: "${{ github.repository_owner }}",
-                repo: "${{  github.repository }}".split('/')[1],
-                per_page: per_page,
-                page: page
-              })
-              for (entry in result.data) {
-                tag_name = result.data[entry].name
-                if (tag_name.startsWith(branch_part)) {
-                  patch_no = parseInt(tag_name.substring(branch_part.length + 1))
-                  if (max_patch_no <= patch_no) {
-                    max_patch_no = patch_no + 1
+            latest_tag = '0.0.0'
+            // process multiple tags if any
+            tags = "${{ env.TAGS }}".split(' ')
+            if (tags.length == 1) {
+              latest_tag = tags[0]
+            } else {
+              if ("${{ github.event.pull_request.base.ref }}" == "main") {
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("Checking tag " + tag)
+                  if (latest_tag == null) {
+                    latest_tag = tag
+                    continue
+                  }
+                  latest_parts = latest_tag.split(".")
+                  tag_parts = tag.split(".")
+                  for (i = 0; i < tag_parts.length; i++) {
+                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
+                      console.log("Skipping " + tag)
+                      break
+                    }
+                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
+                      latest_tag = tag
+                      console.log("Setting " + latest_tag)
+                      break
+                    }
+                  }
+                }
+              } else {
+                tag_base = "${{ github.event.pull_request.base.ref }}".substring(4).split(".").slice(0,2)
+                latest_tag = tag_base.join(".") + ".0"
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("branch - Checking tag " + tag)
+                  tag_parts = tag.split(".")
+                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
+                    latest_parts = latest_tag.split(".")
+                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                      latest_tag = tag
+                    }
                   }
                 }
               }
-              if (result.data.length == per_page) {
-                page = page + 1
-              } else {
-                break;
-              }
             }
-            tag = branch_part + '.' + max_patch_no
-            core.setOutput('tag_name', tag)
+            console.log("Latest tag: " + latest_tag)
 
-      - name: Create tag
-        uses: actions/github-script@v4
-        with:
-          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
-          script: |
-            tag = "${{ steps.latest_tag.outputs.tag_name }}"
-            sha_to_tag = "${{ steps.commit.outputs.commit_to_tag }}"
-            repo_name = "${{  github.repository }}".split('/')[1]
-            console.log("Creating tag," + tag + " against commit " + sha_to_tag)
+            // check if we have
+            if ( latest_tag == '' || latest_tag === undefined) {
+              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
+              process.exit(1);
+            }
 
-            result = await github.git.createTag({
+            // increase the minor version lineraly to get the new tag
+            tag_parts = latest_tag.split('.')
+            new_tag = [tag_parts[0], tag_parts[1], parseInt(tag_parts[2]) + 1].join('.')
+
+            // head of the branch needs to be tagged
+            sha_to_tag = "${{ github.event.pull_request.merge_commit_sha }}"
+
+            console.log("Creating tag: " + new_tag + " against commit " + sha_to_tag)
+
+            result = await github.rest.git.createTag({
                 owner: "${{ github.repository_owner }}",
-                repo: repo_name,
-                tag: tag,
+                repo: "${{  github.repository }}".split('/')[1],
+                tag: new_tag,
                 message: 'Tag created by CI pipeline',
                 type: 'commit',
                 object: sha_to_tag
-            })
+            });
+
             console.log(result)
-            fullTagName = "refs/tags/" + tag
-            console.log("Creating tag..." + tag)
-            console.log("Updating tag..." + fullTagName)
-            newRef = await github.git.createRef({
+
+            fullTagName = "refs/tags/" + new_tag
+
+            console.log("Updating tag with REF: " + fullTagName)
+
+            newRef = await github.rest.git.createRef({
                 owner: "${{ github.repository_owner }}",
-                repo: repo_name,
+                repo: "${{  github.repository }}".split('/')[1],
                 ref: fullTagName,
                 sha: sha_to_tag
-            })
+            });
             console.log('Ref updated.');
-            core.setOutput('tag_ref', fullTagName)
+            core.setOutput('tag_ref', new_tag)  
+
+      - name: Tag Output
+        id: tag_output
+        run: |
+          echo "tag_ref=${{steps.create_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
+
+      - name: Set Label
+        id: set_label
+        shell: bash
+        run: |
+          if [ -f convoy.yaml ]; then
+            echo "convoy_exists=true" >> $GITHUB_OUTPUT
+            if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+              TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
+              APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
+              URL="http://api.convoy.tessell.cloud/devops/applications/app-groups/$APP_GROUP/latest-main-release-label"
+              RESPONSE=$(curl -f --location "$URL" --header "Authorization: Basic $TOKEN")
+              echo "$RESPONSE"
+              LABEL=$(echo "$RESPONSE" | jq -r '.["latest-main-release-label"]')
+              echo "$LABEL"
+              if [[ $LABEL == rel-* ]]; then
+                  echo "LABEL=$LABEL" >> $GITHUB_ENV
+              else
+                  echo "Response: $LABEL"
+                  echo "Label does not start with 'rel'. Check response."
+                  exit 1 
+              fi
+            else
+              echo "LABEL=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+            fi
+           else
+            echo "convoy.yaml not found"
+            echo "convoy_exists=false" >> $GITHUB_OUTPUT
+           fi 
+
+      - name: Validate Label
+        if: ${{ steps.set_label.outputs.convoy_exists == 'true' }}
+        run: |
+          tag=$(echo ${{steps.create_tag.outputs.tag_ref}} | cut -d '.' -f 2)
+          label=$(echo ${{env.LABEL}} | cut -d '.' -f 2)
+          if [ "$tag" == "$label" ]; then
+              echo "TAG and LABEL are on same release label: rel-$TAG"
+          else
+              echo "TAG and LABEL are on different release label. Please check git tag and API response."
+              exit 1
+          fi   
+
+      - name: Slack Notification
+        uses: act10ns/slack@v1.5.0
+        with:
+           status: ${{ job.status }}
+           steps: ${{ toJson(steps) }}
+           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}
+        if: failure()
+
+  push-commit-details-to-convoy: 
+    runs-on: ubuntu-latest
+    needs: create-tag-on-merge
+    env:
+      SLACK_WEBHOOK_URL: ${{ secrets.CONVOY_ALERTS_SLACK_URL }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          ref: ${{github.event.pull_request.base.ref}}
+          fetch-depth: 0
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install requests pyyaml pybase64
+
+      - name: POST API to Convoy
+        env:
+          API_URL: http://api.convoy.tessell.cloud/devops/git-metadata/commits
+          COMMIT_HASH: "${{github.sha}}"
+          REPO: "${{github.event.pull_request.base.repo.name}}"
+          TAG: "${{needs.create-tag-on-merge.outputs.tag_ref_output}}"
+          BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
+          PR_ID: "${{github.event.number}}"
+          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
+          USER: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+        run: |
+          python - <<EOF
+          
+          import yaml
+          import requests
+          import os
+          import time
+          import base64
+          import subprocess
+
+          def delete_keys(data, keys_to_exclude):
+            for key in keys_to_exclude:
+                try:
+                    del data[key]
+                except:
+                    print(f'{key} not present in convoy.yaml')
+            return data
+          
+          def get_artifacts(generates, version):
+              artifacts=[]
+              for artifact_type, artifact in generates.items():
+                  for object in artifact:
+                    element={}
+                    element["type"] = artifact_type
+                    try:
+                      element["releaseManifestKey"] = object["releaseManifestKey"] 
+                    except:
+                        print("Artifact excluded from Release Manifest") 
+                        return
+                    element["name"] = object["name"]
+                    element["version"] = version
+                    if artifact_type == 'helmCharts':
+                      chart_path = object["chartPath"]
+                      with open(chart_path, 'r') as chart_yaml_content:
+                        data = yaml.safe_load(chart_yaml_content)
+                      element["version"] = data.get('version')
+                    try:
+                      element["extension"] = object["extension"]
+                    except:
+                      print("Extension Details not present")
+                    artifacts.append(element)
+              return artifacts
+          
+          def post_request(payload):
+            API_URL = os.environ.get('API_URL')
+            CONVOY_AUTH_TOKEN = os.environ.get('USER')+':'+ os.environ.get('GITHUB_TOKEN')
+            CONVOY_AUTH_TOKEN = base64.b64encode(CONVOY_AUTH_TOKEN.encode('utf-8')).decode('utf-8')
+            headers = {
+              'Authorization': f'Bearer {CONVOY_AUTH_TOKEN}',
+              'Content-Type': 'application/json'
+            }
+            max_retries = 3
+            retry_delay = 5 
+
+            for _ in range(max_retries):
+                response = requests.post(API_URL, json=payload, headers=headers)
+                if response.status_code == 200 or response.status_code == 409:
+                    print(response.status_code)
+                    print(response.text)
+                    break
+                else:
+                    print(response.status_code)
+                    print(response.text)
+                    print(f"Retrying... ({max_retries - _} attempts left)")
+                    time.sleep(retry_delay)
+            else:
+                print("API request failed after retries.")
+                exit(1)
+            print("POST request Complete")
+            return
+            
+          REPO = os.environ.get('REPO')
+          COMMIT_HASH = os.environ.get('COMMIT_HASH')
+          BASE_BRANCH = os.environ.get('BASE_BRANCH')
+          PR_ID = os.environ.get('PR_ID')
+          TAG = os.environ.get('TAG')
+          COMMIT_MESSAGE = subprocess.check_output(['git','log','--pretty=format:%s','-n','1'])
+          COMMIT_MESSAGE = COMMIT_MESSAGE.decode('utf-8')
+
+          try:
+            with open('convoy.yaml', 'r') as yaml_file:
+                yaml_data = yaml.safe_load(yaml_file)
+          except FileNotFoundError:
+              print(f"YAML file not found. Skipping this step.")
+              exit(0)
+          payload = { 
+            "repoName": REPO,
+            "commitHash": COMMIT_HASH[:7],
+            "commitMessage": COMMIT_MESSAGE,
+            "baseBranch": BASE_BRANCH,
+            "tag": TAG,
+            "pullRequestId": PR_ID,
+          }
+          generates = yaml_data.get('generates')
+          type = yaml_data.get('artifactType') 
+          if generates != None:
+              version = yaml_data.get('version')
+              if version == None:
+                version = TAG
+              payload["artifacts"] = get_artifacts(generates, version)
+              if payload["artifacts"] == None:
+                del payload["artifacts"]
+              print(payload)
+          elif type == None:
+              print(payload)
+          else: 
+              payload["artifactMetadata"] = get_artifact_metadata(yaml_data,type)
+              print(f"Payload: {payload}")
+          post_request(payload)
+          EOF
+
+      - name: Slack Notification
+        uses: act10ns/slack@v1.5.0
+        with:
+            status: ${{ job.status }}
+            steps: ${{ toJson(steps) }}
+            channel: ${{ secrets.CONVOY_ALERTS_SLACK_CHANNEL  }}
+        if: failure()
diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -1,4 +1,4 @@
-# This is a basic workflow to help you get started with Actions
+---
 name: Best Practices Check
 
 # Controls when the workflow will run
@@ -6,21 +6,29 @@ on:
   pull_request:
     branches:
       - 'main'
-      - 'rel-**'
-      - 'TS-*'
+      - 'rel-*'
+      - 'TS-*' 
+      - 'TDEVOPS-*'
+      - 'revert-*'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   dev-checks:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: |
+          echo "$GITHUB_CONTEXT"
+
+      - uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
+          fetch-depth: 0
+
       - name: Get branch name (merge)
         if: github.event_name != 'pull_request'
         shell: bash
@@ -31,12 +39,238 @@ jobs:
         if: github.event_name == 'pull_request'
         shell: bash
         run: |
-          echo "SOURCE_BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
+          echo "SOURCE_BRANCH=$(echo ${{ github.event.pull_request.head.ref }} | tr / -)" >> $GITHUB_ENV
           echo "TARGET_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
-        
-      # Check if branch name is according to the guidelines
-      - name: Check branch name
-        if: ${{ !startsWith(env.SOURCE_BRANCH,'TS-') }}
+          echo "GITHUB_TOKEN=${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}" >> $GITHUB_ENV
+      
+      - name: Check Format
+        env:
+          PR_TITLE: ${{ github.event.pull_request.title }}
         run: |
-          echo "::debug::Branch name must start with 'TS-' ${{ env.SOURCE_BRANCH }}"
-          exit 1
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-'; then
+              echo "Revert branch, skipping Format check"
+              exit 0
+          fi
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^(TS-|SRE-|TDEVOPS-|TOPS-)'; then
+            echo "Branch name starts with 'TS-' or 'SRE-' or 'TDEVOPS-' or 'TOPS-'"
+          else
+            echo "Branch name does not start with 'TS-' or 'SRE-' or 'TDEVOPS-' or 'TOPS-'. Checking PR title format."
+            PULL_REQUEST_TITLE="$PR_TITLE"
+            PATTERN="(TS|TDEVOPS|TOPS|SRE)-[0-9]+\s\|\s"
+            if [[ ! $PULL_REQUEST_TITLE =~ $PATTERN ]]; then
+              echo "Error: Pull request title is not in the required format. Please use 'TS-XXXX | --' or 'TDEVOPS-XXXX | --' or 'TOPS-XXXX | --' or 'SRE-XXXX | --' format."
+              exit 1
+            else 
+              echo "PR Title is in the valid format."
+            fi  
+          fi
+
+      - name: Check convoy.yaml
+        id: convoy_check
+        run: |
+          if [ -f "convoy.yaml" ]; then
+            echo "convoy_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "convoy_exists=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install shyaml
+          echo ${{steps.convoy_check.outputs.convoy_exists}}
+
+      - name: Check double commit
+        env: 
+          PR_TITLE: ${{github.event.pull_request.title}}
+          BRANCH: ${{ github.event.pull_request.head.ref}}
+        run: |
+          if ([[ '${{ github.event.pull_request.user.login }}' != 'cipipelinetessell' ]]) && ([[ "$BRANCH" == *"double_commit"* ]] || [[ "$PR_TITLE" == *"Double Commit"* ]]); then
+            if ([[ "$BRANCH" == *"revert"* ]] && [[ "$PR_TITLE" == *"Revert"* ]]); then
+              echo "Revert Double commit Branch. Allowed"
+            else   
+              echo "Exclude Double commit naming in Branch, PR title and try again."
+              exit 1
+            fi
+          else
+            echo "No double commit conflicts found in Branch or PR title."
+          fi
+
+      - name: import packages for json lint
+        run: |
+          sudo sudo npm install jsonlint -g
+          
+      - name: Check for Jsonlint
+        run: |
+          set -e
+          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
+
+      - name: install octokit/rest
+        run: |
+          if [ ! -d "node_modules/@octokit/rest" ]; then
+            npm cache clean --force
+            npm install @octokit/rest --legacy-peer-deps
+          fi
+      - name: install node fetch 
+        run: | 
+          npm install node-fetch 
+
+      - name: Install dependencies
+        run: npm install js-yaml
+
+      - name: Check for merge conflicts
+        uses: actions/github-script@v6.4.1
+        with:
+          github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
+          script: |
+            head_commit = "${{ github.sha }}"
+            base_commit = "${{ github.sha }}"
+            if ( "${{ github.event.before }}" != '0000000000000000000000000000000000000000') { 
+              base_commit = "${{ github.event.before }}"
+            }
+            if ( "${{ github.event_name }}" == 'pull_request') {
+              console.log("Using the base branch's commit for comparing.")
+              base_commit = "${{ github.event.pull_request.base.sha  }}"
+            }
+            response = await github.rest.repos.compareCommits({
+                owner: "${{ github.repository_owner }}",
+                repo: "${{  github.repository }}".split('/')[1],
+                head: head_commit,
+                base: base_commit
+            });
+            response.data.files.forEach(function(file_entry) {
+              console.log(file_entry.filename);
+              dir_name = file_entry.filename.split("/")[0];
+              console.log(file_entry.patch);
+              if(typeof file_entry.patch !== 'undefined'){
+                if ( file_entry.patch.includes("+<<<<<<<") || file_entry.patch.includes("+=======") || file_entry.patch.includes("+>>>>>>>")) {
+                  core.setFailed("Please resolve Merge Conflict in: " + dir_name );  
+                }
+              }
+              else{
+                console.log("Skipping:" + file_entry.filename);
+              }
+            });
+            console.log("No merge conflicts found"); 
+            
+      - name: Check version in convoy.yaml and gradle.properties
+        id: check_convoy
+        run: |
+            if [ -f convoy.yaml ]; then
+              if grep -q 'version:' convoy.yaml; then
+                echo "Version found in convoy.yaml"
+                
+                if [ -f gradle.properties ]; then
+                  if grep -q '^\s*version=' gradle.properties; then
+                    echo "Please remove version from gradle.properties"
+                    exit 1
+                  else
+                    echo "check_version_in_gradle=true" >> $GITHUB_OUTPUT
+                  fi
+                fi
+              else
+                echo "Version not found in convoy.yaml"
+                echo "check_version_in_gradle=false" >> $GITHUB_OUTPUT
+              fi
+            else
+              echo "convoy.yaml not found"
+              echo "check_version_in_gradle=false" >> $GITHUB_OUTPUT
+            fi
+            
+      - name: check for gradle properties version
+        uses: actions/github-script@v6.3.3
+        with:
+          github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
+          script: |
+            head_commit = "${{ github.sha }}"
+            base_commit = "${{ github.sha }}"
+            if ( "${{ github.event.before }}" != '0000000000000000000000000000000000000000') { 
+              base_commit = "${{ github.event.before }}"
+            }
+            if ( "${{ github.event_name }}" == 'pull_request') {
+              console.log("Using the base branch's commit for comparing.")
+              base_commit = "${{ github.event.pull_request.base.sha  }}"
+            }
+            console.log("base_commit " + base_commit);
+            console.log("head_commit " + head_commit); 
+            response = await github.rest.repos.compareCommits({
+                owner: "${{ github.repository_owner }}",
+                repo: "${{  github.repository }}".split('/')[1],
+                head: head_commit,
+                base: base_commit
+            });
+            version_updated = false
+             response.data.files.forEach(function(file_entry) {
+               if (file_entry.filename == 'convoy.yaml') {
+                   console.log(file_entry.patch)
+                   if (file_entry.patch.includes("-version:") && file_entry.patch.includes("+version:")) {
+                       version_updated = true
+                   }
+               }
+             });
+             if (version_updated == false) {
+                  core.setFailed("Tessell Libraries must update the version in gradle.properties file")
+             }
+
+      - name: check for terraform (code)
+        if : github.event_name == 'pull_request'
+        id: terraform_check
+        uses: actions/github-script@v6.3.3
+        with:
+          github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
+          script: |
+            head_commit = "${{ github.sha }}"
+            base_commit = "${{ github.sha }}"
+            if ( "${{ github.event.before }}" != '0000000000000000000000000000000000000000') { 
+              base_commit = "${{ github.event.before }}"
+            }
+            if ( "${{ github.event_name }}" == 'pull_request') {
+              console.log("Using the base branch's commit for comparing.")
+              base_commit = "${{ github.event.pull_request.base.sha  }}"
+            }
+            console.log("base_commit " + base_commit);
+            console.log("head_commit " + head_commit); 
+            response = await github.rest.repos.compareCommits({
+                owner: "${{ github.repository_owner }}",
+                repo: "${{  github.repository }}".split('/')[1],
+                head: head_commit,
+                base: base_commit
+            });
+            var terraform_file = [] 
+            response.data.files.forEach(function(file_entry) {
+              if (file_entry.filename.endsWith(".tf") && file_entry.status != 'removed') {
+                console.log(file_entry.filename);
+                console.log(file_entry.status);
+                terraform_file.push(file_entry.filename)
+                console.log(terraform_file) ;
+              }
+            });
+            core.setOutput('terraform_file' , terraform_file.join(','));
+
+
+      - name: Check Version sequence of DB Scripts
+        id: check_db_version_seq
+        if: steps.check_db_migration.outputs.db_migration_dir
+        run:
+          python3 .github/scripts/check_db_migration_version_sequence.py "${{ steps.check_db_migration.outputs.db_migration_dir }}"      
+      
+
+      - name: check for terraform version
+        if: steps.terraform_check.outputs.terraform_file 
+        run:
+          terraform_version_check "${{ steps.terraform_check.outputs.terraform_file }}"
+      
+      - name: check to verify same branch is exist
+        if: ${{ startsWith(env.TARGET_BRANCH,'rel-') && !contains(env.SOURCE_BRANCH,'double_commit') }}
+        run: |
+          branch_to_check=${{ env.SOURCE_BRANCH }}-main-double_commit
+          list_of_branches=($(git branch -r | awk -F '/' '{print $2}'))
+          for branch in "${list_of_branches[@]}";do
+          if [[ "$branch" == "$branch_to_check" ]];then
+            echo "Double commit branch with name $branch is alredy exist , please merge and/or delete  the branch ";exit 1;
+          fi
+          done
+             
